const ENDPOINT_GET_STATIC_PAGES = 'content/pages'
const ENDPOINT_GET_STATIC_PAGE_CONTENT = 'content/page/'
const ENDPOINT_GET_SEARCH = 'search'

export {ENDPOINT_GET_STATIC_PAGES, ENDPOINT_GET_STATIC_PAGE_CONTENT, ENDPOINT_GET_SEARCH}
